[phases.setup]
nixPkgs = ["python311", "gcc"]
aptPkgs = ["python3-pip"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python -m ensurepip --upgrade || true",
    "python -m pip install --no-cache-dir -r requirements-prod.txt || python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT --workers 1"

[variables]
PYTHONPATH = "/app"