services:
  - name: deckster-api
    build:
      context: .
      dockerfile: null
    deploy:
      startCommand: python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT --workers 1
      healthcheckPath: /health
      restartPolicyType: ON_FAILURE
      restartPolicyMaxRetries: 10
    envVars:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
      APP_ENV: production